### ISSUE TITLE
SAS token support 

### ISSUE THREAD

**Issue by georgesmarkus** [jakeFeldman/strapi-provider-upload-azure-storage#70]
Hi,
The plug-in does not support SAS token, currently the blob must allow anonymous access .
Regards

**Comment by jakeFeldman** [comment]
SAS tokens should be supported. How is your key being formatted?

https://github.com/jakeFeldman/strapi-provider-upload-azure-storage/blob/master/src/index.ts#L49

**Comment by PedroDAI** [comment]
> SAS tokens should be supported. How is your key being formatted?
> 
> https://github.com/jakeFeldman/strapi-provider-upload-azure-storage/blob/master/src/index.ts#L49

Hey there!

I'm also having the issue where even if I pass the `sasToken` key in the configuration, without passing the `accountKey` at the same time, the provider doesn't seem to be making use of it.

I checked the package's code for the latest version (3.1.3) in my `node_modules` folder, and it seems like the `index.ts` file there doesn't contain the latest changes to make use of the `sasToken`.

So it seems to me that maybe there is a new release with those changes to be done? Or am I missing something?

Thanks in advance!

**Comment by jakeFeldman** [comment]
@PedroDAI Thanks for reporting. Let me look into this. Maybe 3.1.3 is a bad build

**Comment by derBretti** [comment]
Since 3.1.3 is the latest build that's publicly available, the issue isn't actually resolved, right? It works with a build from the master branch, so it would be nice to have a new public build with the fix.
Apart from that, I noticed, that the SAS token is stored in the URL, which means that files become inaccessible by the URL provided if the token expires. Wouldn't it be better to add the token to the URL when the file is requested?
